### ISSUE TITLE
Undocumented JS parsing

### ISSUE THREAD

**Issue by mcmulman** [magepow/magento2-lazyload#1]
https://github.com/magepow/magento-2-lazy-load/blob/6483453812d1eab6f256b75af9f9895e38f9e79b/Plugin/LazyResponse.php#L86

Hey,
why are you doing a replace for <script> tags?
I would only like to use the image handling.

This "feature" is not documented and not configurable.
Also it causes errors for some json content within script tags.

What is it needed for?

Thanks,
Mathias

**Comment by magiccart** [comment]
This code to exception tag img use in javascript example captcha ...etc
